server:
  port: 8080
  servlet:
    context-path:

spring:
  datasource:
    url: jdbc:mysql://nj-cynosdbmysql-grp-3ugamqal.sql.tencentcdb.com:29422/fenglish?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root1
    password: ABCabc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        # 强制使用@Table指定的表名，不做自动转换
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # 替换过时方言
        format_sql: true
        jdbc:
          time-zone: Asia/Shanghai

logging:
  level:
    com.nuaa.englishlearning: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

